---
# tasks file for ansible-linux-security-role
# Linux Malware Detect isn't available as a package
# Lynis updates often and package tends to be behind
# everything else is apt-get installed.

  - name: make sure the time is correct
    shell: "ntpdate -u pool.ntp.org"

  - name: Update APT package cache
    action: apt update_cache=yes

  - name: install packages
    apt:
      pkg: "{{ item }}"
      state: latest
    with_items:
      - chkrootkit
      - lsat
      - nmap
      - rkhunter
      - tiger
      - zip

  - name: rkhunter | Make sure rkhunter has latest defs
    command: rkhunter --propupd

  - name: Create root's download dir
    file: path=/root/downloads state=directory
    file: path=/root/downloads/maldet state=directory
    file: path=/root/downloads/lynis state=directory
 
  - name: Maldet | download the Linux Malware Detect tar.gz file from rfxn.com
    get_url:
      url=http://www.rfxn.com/downloads/maldetect-current.tar.gz
      dest="/root/downloads/maldetect-current.tar.gz"
    tags: maldet

  - name: Maldet | Untar Linux Malware Detect tar.gz
    command: mkdir /root/downloads/maldet/ 
    ignore_errors: yes
    tags: maldet

  - name: Maldet | Untar Linux Malware Detect tar.gz
    command: tar xvfz /root/downloads/maldetect-current.tar.gz -C /root/downloads/maldet/ --strip-components 1
    tags: maldet

  - name: Maldet | Install Linux Malware Detect
    shell: /root/downloads/maldet/install.sh chdir=/root/downloads/maldet/
    tags: maldet

  - name: Maldet | Add maldet to crontab
    cron: name="Run Maldet" hour="{{ 3|random}}" minute="{{ 57 |random}}" job="{{ maldet_cron }}" state=present
    tags: lynis
    tags: cron

  - name: Lynis | Grab the latest Lynis
    get_url: url=https://cisofy.com/files/{{ lynis_version }} dest=/root/downloads
    tags: lynis

  - name: Lynis | Unarchive copied package
    unarchive: src=/root/downloads/{{ lynis_version }} dest=/root/downloads/lynis/ copy=yes
    tags: lynis

  - name: Lynis | Install Lynis
    command: mv /root/downloads/lynis /etc/lynis chdir=/root/downloads/lynis creates=/etc/lynis
    tags: lynis

  - name: Lynis | Add Lynis to crontab
    cron: name="Run Lynis" hour="{{ 4|random}}" minute="{{ 59 |random}}" job="{{ lynis_cron }}" state=present
    tags: lynis
    tags: cron
